# Generated by Django 3.1.7 on 2021-04-22 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='年齢区分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='附属設備・器具')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='利用体育施設の名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='団体名')),
                ('reader_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='代表者名')),
                ('contact_name', models.CharField(max_length=25, verbose_name='連絡者名')),
                ('address', models.CharField(max_length=125, verbose_name='住所')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='電話番号')),
                ('is_group', models.BooleanField(default=False, verbose_name='is_group')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete_flag')),
                ('start', models.DateTimeField(verbose_name='利用開始日時')),
                ('end', models.DateTimeField(verbose_name='利用終了日時')),
                ('organizer_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='主催関係者数')),
                ('participant_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='参集人員数')),
                ('purpose', models.TextField(max_length=75, verbose_name='利用目的')),
                ('admission_fee', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='入場料の徴収')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_equipments', to='reservations.equipment', verbose_name='equipments')),
                ('places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_places', to='reservations.place', verbose_name='places')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='特別設備')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='利用区分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='団体名')),
                ('reader_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='代表者名')),
                ('contact_name', models.CharField(max_length=25, verbose_name='連絡者名')),
                ('address', models.CharField(max_length=125, verbose_name='住所')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='電話番号')),
                ('is_group', models.BooleanField(default=False, verbose_name='is_group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info_users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='UsageCategorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_categorizes_reservations', to='reservations.reservation', verbose_name='reservations')),
                ('usages', models.ManyToManyField(related_name='usage_categorizes_usages', to='reservations.Usage', verbose_name='usages')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_equipments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resercvations_special_equipments', to='reservations.specialequipment', verbose_name='special_equipments'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.CreateModel(
            name='DefferdPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='後納の理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defferd_payments_reservations', to='reservations.reservation', verbose_name='reservations')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='利用料')),
                ('heating_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='暖房料')),
                ('electric_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='電気料')),
                ('conditions', models.TextField(max_length=255, verbose_name='承認の条件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_apps_approvals', to='reservations.approval', verbose_name='approvals')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_apps_reservations', to='reservations.reservation', verbose_name='reservations')),
            ],
        ),
        migrations.CreateModel(
            name='AgeCategorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ages', models.ManyToManyField(related_name='age_categorizes_usages', to='reservations.Usage', verbose_name='ages')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categorizes_reservations', to='reservations.reservation', verbose_name='reservations')),
            ],
        ),
    ]
