# Generated by Django 3.2.8 on 2021-10-26 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usagecategory',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_category_reservation', to='reservations.reservation', verbose_name='reservation'),
        ),
        migrations.AddField(
            model_name='usagecategory',
            name='usage',
            field=models.ManyToManyField(related_name='usage_category_usage', to='reservations.Usage', verbose_name='usage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='reservation_equipment', to='reservations.Equipment', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_place', to='reservations.place', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_equipment',
            field=models.ManyToManyField(blank=True, related_name='resercvation_special_equipment', to='reservations.SpecialEquipment', verbose_name='special_equipment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='facilityfee',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_fee_age', to='reservations.age', verbose_name='age'),
        ),
        migrations.AddField(
            model_name='facilityfee',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_fee_place', to='reservations.place', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='facilityfee',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_fee_time', to='reservations.time', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='equipmentfee',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_fee_equipment', to='reservations.equipment', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='place',
            field=models.ManyToManyField(related_name='equipment_place', to='reservations.Place', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='defferdpayment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defferd_payment_reservation', to='reservations.reservation', verbose_name='reservation'),
        ),
        migrations.AddField(
            model_name='approvalapplication',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_app_approval', to='reservations.approval', verbose_name='approval'),
        ),
        migrations.AddField(
            model_name='approvalapplication',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_app_reservation', to='reservations.reservation', verbose_name='reservation'),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='age',
            field=models.ManyToManyField(related_name='age_category_age', to='reservations.Age', verbose_name='age'),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_category_reservation', to='reservations.reservation', verbose_name='reservation'),
        ),
    ]
