# Generated by Django 3.2.7 on 2021-10-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='書類名')),
                ('url', models.TextField(blank=True, null=True, verbose_name='ファイルパス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='発行番号')),
                ('file_name', models.CharField(max_length=30, verbose_name='ファイル名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_approvalapplication', to='reservations.approvalapplication', verbose_name='document_approvalapplication')),
            ],
        ),
    ]
