# Generated by Django 3.2.8 on 2021-10-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_documents', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_approvalapplication', to='reservations.approvalapplication', verbose_name='document_approvalapplication'),
        ),
    ]
