@startuml entity-relationship-diagram

scale 1.5
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam linetype ortho

skinparam sequence {
  ActorFontSize 28
  ParticipantFontSize 28
  ArrowFontSize 28
  titleFontSize 28
}
skinparam UsecaseStereotypeFontSize  28

skinparam usecase {
  BackgroundColor DarkSeaGreen
  BorderColor DarkSlateGray
}

skinparam actor {
        BackgroundColor #333333
        BorderColor #999999
}

package "予約システム・管理システム共通" as Common {
    Class "usersマスタ" as users <<M,AAFFAA>> {
        +id [pk]
        --
        email : email
        password
    }
}
' rectangle 予約システム {
'   ユーザー --|> (利用登録)
'   note right : 名前、メールアドレス、住所、パスワードを登録
'   ユーザー --|> (施設エリアを選択)
'   ユーザー -left-|> (予約状況を確認)
'   ユーザー --|> (予約日前日にリマインドメールを受信)
'   ユーザー --|> (施設の予約料金を確認)
'   ユーザー --|> (施設使用後レビュー案内メールを受信)

'   (施設エリアを選択) --|> (仮予約)
'   (仮予約) -left-|> (予約状況を”仮予約”状態に更新)
'   (予約状況を”仮予約”状態に更新) --|> (予約情報を施設側に送信)
'   (予約情報を施設側に送信) --|> (承認メールを受信) : 承認
'   (予約情報を施設側に送信) --|> (拒否メールを受信) : 拒否
'   (承認メールを受信) ---|> (使用申請書を添付してメール送信) : 使用申請書作成
'   (承認メールを受信) --|> (予約キャンセル)
'   (予約状況を確認) -left-|> (予約キャンセル)
'   (予約キャンセル) --|> (還付案内メールを受信) : 使用料が納付済の場合
' }
' rectangle 予約システム・予約管理システム共通 {
'   ユーザー --|> (ログイン・ログアウト)
'   ユーザー -|> (登録情報の変更・削除)
'   施設側 --|> (ログイン・ログアウト)
'   施設側 --|> (登録情報の変更・削除)
' }

' rectangle 予約管理システム {
'   施設側 --|> (予約申請のメールを受信)
'   施設側 --|> (予約者の顧客情報を管理)
'   施設側 --|> (今までの施設の利用状況データを確認)
'   施設側 -|> (レビューを管理)
'   (予約申請のメールを受信) -|> (承認メールを送信)
'   (予約申請のメールを受信) --|> (拒否メールを送信)
'   (承認メールを送信) -|> (予約状況を更新)
'   (拒否メールを送信) -|> (予約状況を更新)
'   (予約状況を更新) -|> (予約状況をホームページに貼り付け)
' }
@enduml
