# Generated by Django 3.1.7 on 2021-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=10, verbose_name='記入者')),
                ('content', models.CharField(max_length=50, verbose_name='業務内容')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('end', models.DateTimeField(verbose_name='終了日時')),
                ('other', models.CharField(blank=True, max_length=50, null=True, verbose_name='その他')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
