# Generated by Django 3.1.7 on 2021-03-24 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdiary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
