# Generated by Django 3.2.9 on 2021-11-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings_user', to=settings.AUTH_USER_MODEL, verbose_name='app_settings_user'),
        ),
    ]
