# Generated by Django 4.0 on 2022-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_appsettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='auto_mail_name')),
                ('subject', models.CharField(max_length=255, verbose_name='auto_mail_subject')),
                ('body', models.TextField(verbose_name='auto_mail_body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
