@startuml entity-relationship-diagram

scale 1.5
left to right direction
skinparam packageStyle rectangle
skinparam linetype ortho


!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "予約システム・管理システム共通" as Common {
    entity "Usersマスタ" as users <<M,MASTER_MARK_COLOR>> {
        + id [pk]
        --
        email : email
        password : char 8-16
    }
}

package "予約システム" as reservation_system {
  entity "Reservationsテーブル" as reservations <<主,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
    + id [pk]
    --
    # users [fk]
    group_name : char 25
    reader_name : char 25
    contact_name : char 25
    address : char 125
    TEL : phone number
    is_group : bool
    delete_flag : bool
    start : date
    end : date
    organizer_number : int 255
    participant_number : int 255
    purpose : text 75
    admission_fee : int 10000
    # places [fk]
    # equipments [fk]
    # special_equipments [fk]
  }

  entity "User_infoテーブル" as user_info <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [pk]
    --
    # users [fk]
    group_name : char 25
    reader_name : char 25
    contact_name : char 25
    address : char 125
    TEL : phone number
    is_group : bool
  }

  entity "Approval_applicationsテーブル" as approval_apps <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [pk]
    --
    # reservations [fk]
    usage_fee : int 20000
    heating_fee : int 20000
    electric_fee : int 20000
    condition : text 255
    # approvals [fk]
  }

  entity "Usage_categorizesテーブル" as usage_categorize <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [pk]
    --
    # reservations [fk]
    # usages [fk]
  }

  entity "Age_categorizesテーブル" as age_categorize <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [pk]
    --
    # reservations [fk]
    # ages [fk]
  }

  entity "Deferred_paymentsテーブル" as defferd_payments <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [pk]
    --
    reason : char 50
    # reservations [fk]
  }

  entity "Placesマスタ" as places <<M,MASTER_MARK_COLOR>> {
    + id [pk]
    --
    name : char 25
  }

  entity "Equipmentsマスタ" as equipments <<M,MASTER_MARK_COLOR>> {
    + id [pk]
    --
    name : char 25
  }

  entity "Spacial_equipmentsマスタ" as special_equipments <<M,MASTER_MARK_COLOR>> {
    + id [pk]
    --
    name : char 25
  }

  entity "Agesマスタ" as ages <<M,MASTER_MARK_COLOR>> {
     + id [pk]
    --
    name : char 25
  }

  entity "Usagesマスタ" as usages <<M,MASTER_MARK_COLOR>> {
    + id [pk]
    --
    name : char 25
  }

  entity "Approvalsマスタ" as approvals <<M,MASTER_MARK_COLOR>> {
     + id [pk]
    --
    name : char 25
  }
}

users             |o--o{    reservations
users             |o--o{    user_info
reservations      ||--|{    places
reservations      ||--|{    equipments
reservations      ||--|{    special_equipments
approval_apps     ||--||    reservations
age_categorize    ||--||    reservations
usage_categorize  ||--||    reservations
defferd_payments  ||--||    reservations
approval_apps     ||--|{    approvals
age_categorize    ||--|{    ages
usage_categorize  ||--|{    usages
@enduml
